default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.6.2
    hooks:
      - id: pyupgrade
        args: [--keep-percent-format, --py3-plus]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.0.4
    hooks:
      - id: isort
        name: Sort imports
        types: [python]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Check python formatting
        args: [--line-length=80, --skip-string-normalization, --check, --diff]
        language_version: python3.7
        stages: [manual]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Format python
        args: [--line-length=80, --skip-string-normalization]
        language_version: python3.7

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        name: Check python
        additional_dependencies:
          - flake8-bugbear==20.1.4
          - pep8-naming==0.11.1
          - flake8-quotes==3.2.0
          - flake8-logging-format==0.6.0
          - flake8-comprehensions==3.2.3
          - flake8-todo==0.7
          - pydocstyle==5.0.2
          - flake8-docstrings==1.5.0
          - flake8-string-format==0.3.0
