default_language_version:
  python: python3.7

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: debug-statements
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: ^.*\.ai$

  - repo: https://github.com/asottile/pyupgrade
    rev: v1.21.0
    hooks:
      - id: pyupgrade
        args: [--keep-percent-format, --py3-plus]

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        name: Sort imports
        types: [python]
        additional_dependencies:
          - isort[pipfile]

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        name: Check python formatting
        args: [--line-length=80, --skip-string-normalization, --check, --diff]
        language_version: python3.7
        stages: [manual]

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        name: Format python
        args: [--line-length=80, --skip-string-normalization]
        language_version: python3.7

  - repo: https://github.com/PyCQA/flake8
    rev: 3.7.8
    hooks:
      - id: flake8
        name: Check python
        additional_dependencies:
          - flake8-bugbear==19.8.0
          - pep8-naming==0.8.2
          - flake8-quotes==2.1.0
          - flake8-logging-format==0.6.0
          - flake8-comprehensions==2.2.0
          - flake8-todo==0.7
          - pydocstyle<4
          - flake8-docstrings==1.3.1
          - flake8-string-format==0.2.3
