- alias: Toggle lights via switch
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001839fab
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000210a4fb
        click_type: single
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: Toggle lights
  action:
    service: light.toggle
    entity_id: all

- alias: Turn off lights via switch
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001839fab
        click_type: long_click_press
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000210a4fb
        click_type: long_click_press
  action:
    service: light.turn_off
    entity_id: all

- alias: Turn off AC via front door switch
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001839fab
        click_type: long_click_press
  action:
    - service: climate.turn_off
      entity_id: climate.thermostat

- alias: Turn on night lights on motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000122955e
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_34ce0088f666
    below: 500
  action:
    - service: light.turn_on
      entity_id:
        - light.gateway_light_34ce0088f666
        - light.under_bed
      data:
        transition: 10
        brightness_pct: 100
        color_name: red

- alias: Turn off night lights after motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000122955e
    to: 'off'
    for:
      seconds: 30
  action:
    service: light.turn_off
    entity_id:
      - light.gateway_light_34ce0088f666
      - light.under_bed
    data:
      transition: 90


- alias: Turn on bathroom vent
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001830feb
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001830feb
      to: 'off'
  action:
    service: switch.turn_on
    entity_id: switch.plug_158d0001640e49

- alias: Turn off bathroom vent
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001830feb
      to: 'on'
      for:
        minutes: 15
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001830feb
      to: 'off'
      for:
        minutes: 15
  action:
    - service: switch.turn_off
      entity_id: switch.plug_158d0001640e49

- alias: Xiaomi Cube - Brightness [Rotate]
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000231e4b8
        action_type: rotate
  action:
    - service: light.turn_on
      entity_id: all
      data_template:
        brightness_step_pct: "{{ trigger.event.data.action_value }}"

- alias: 'AQI warning'
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.aqi
    above: 25
    for: "00:10:00"
  action:
    - service: tts.google_translate_say
      entity_id: media_player.living_room_speaker
      data:
        message: 'Hazardous atmospheric conditions detected'

- alias: 'AQI control'
  trigger:
    platform: time_pattern
    minutes: '/1'
  action:
    - service: xiaomi_miio.fan_set_favorite_level
      entity_id: fan.air_purifier
      data_template:
        level: "{{ [[(states('sensor.aqi') | int / 2) | int, 1] | max, 14] | min }}"
    - service: fan.set_preset_mode
      entity_id: fan.air_purifier
      data:
        preset_mode: Favorite

- alias: AC on
  trigger:
    platform: state
    entity_id: input_boolean.ac
    to: 'on'
  action:
    - service: remote.send_command
      entity_id: 'remote.remote'
      data_template:
        command: "ac_auto_{{ (state_attr('climate.thermostat', 'temperature'))|int }}"

- alias: AC off
  trigger:
    platform: state
    entity_id: input_boolean.ac
    to: 'off'
  action:
    - service: remote.send_command
      entity_id: 'remote.remote'
      data:
        command:
          - 'ac_off'

- alias: 'Sync thermostat with AC'
  trigger:
    platform: state
    entity_id: sensor.target_temperature
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.ac
        state: 'on'
  action:
    - service: remote.send_command
      entity_id: 'remote.remote'
      data_template:
        command: "ac_auto_{{ (state_attr('climate.thermostat', 'temperature'))|int }}"

- alias: 'Sync thermostat off temperature with AC'
  trigger:
    platform: state
    entity_id: sensor.target_temperature
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.ac
        state: 'off'
  action:
    - service: remote.send_command
      entity_id: 'remote.remote'
      data:
        command:
          - 'ac_off'

- alias: 'Sync thermostat off with AC'
  trigger:
    platform: state
    entity_id: climate.thermostat
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: climate.thermostat
        state: 'off'
  action:
    - service: remote.send_command
      entity_id: 'remote.remote'
      data:
        command:
          - 'ac_off'

- alias: Notify when door is opened
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002b6e9f4
    to: 'on'
  condition:
  - condition: state
    entity_id: person.dmytro_sadovnychyi
    state: away
  action:
    - service: notify.notify
      data:
        message: 'Front door has been opened'
