- alias: 'AQI high'
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.aqi
    above: 10
    for:
      seconds: 10
  action:
    - service: tts.google_translate_say
      entity_id: media_player.living_room_speaker
      data:
        message: 'Hazardous atmospheric conditions detected'
    - service: script.ap_max

- alias: 'AQI normal'
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.aqi
    below: 2
    for:
      seconds: 10
  action:
    - service: tts.google_translate_say
      entity_id: media_player.living_room_speaker
      data:
        message: 'AQI at normal value'
    - service: script.ap_auto

- alias: 'Set theme at startup'
  hide_entity: true
  trigger:
   - platform: homeassistant
     event: start
  action:
    service: frontend.set_theme
    data:
      name: material_dark_red

- alias: Update Available Notification
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.notify
      data_template:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
