- alias: Toggle lights via switch
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001839fab
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000210a4fb
        click_type: single
  action:
    service: light.toggle
    entity_id: all

- alias: Turn off lights via switch
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001839fab
        click_type: long_click_press
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d000210a4fb
        click_type: long_click_press
  action:
    service: light.turn_off
    entity_id: all

- alias: Turn off AC via front door switch
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001839fab
        click_type: long_click_press
  action:
    - service: script.ac_off
    # TODO: set away mode
    - service: climate.turn_off
      entity_id: climate.turn_off

- alias: Turn on night lights on motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000122955e
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_34ce0088f666
    below: 500
  action:
    service: light.turn_on
    entity_id: group.night_lights
    data:
      transition: 5

- alias: Turn off night lights after motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000122955e
      to: 'off'
      for:
        seconds: 10
  action:
    - service: light.turn_off
      entity_id: group.night_lights
      data:
        transition: 60

- alias: Turn on bathroom vent
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001830feb
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001830feb
      to: 'off'
  action:
    service: switch.turn_on
    entity_id: group.bathroom_vent

- alias: Turn off bathroom vent
  trigger:
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001830feb
      to: 'on'
      for:
        minutes: 15
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d0001830feb
      to: 'off'
      for:
        minutes: 15
  action:
    - service: switch.turn_off
      entity_id: group.bathroom_vent

- alias: Xiaomi Cube - Brightness [Rotate]
  trigger:
    - platform: event
      event_type: xiaomi_aqara.cube_action
      event_data:
        entity_id: binary_sensor.cube_158d000231e4b8
        action_type: rotate
  action:
    - service: light.turn_on
      entity_id: all
      data_template:
        brightness_step_pct: "{{ trigger.event.data.action_value }}"

- alias: 'AQI warning'
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.aqi
    above: 25
    for: "00:10:00"
  action:
    - service: tts.google_translate_say
      entity_id: media_player.living_room_speaker
      data:
        message: 'Hazardous atmospheric conditions detected'

- alias: 'AQI control'
  trigger:
    platform: time_pattern
    minutes: '/1'
  action:
    - service: script.ap_detect

- alias: AC on
  trigger:
    platform: state
    entity_id: input_boolean.ac
    to: 'on'
  action:
    service: script.turn_on
    data_template:
      entity_id: "script.ac_auto_{{ (state_attr('climate.thermostat', 'temperature')-1)|round }}"

- alias: AC off
  trigger:
    platform: state
    entity_id: input_boolean.ac
    to: 'off'
  action:
    service: script.turn_on
    entity_id: script.ac_off

- alias: 'Sync thermostat with AC'
  trigger:
    platform: state
    entity_id: sensor.target_temperature
  action:
    service: script.turn_on
    data_template:
      entity_id: "script.ac_auto_{{ (state_attr('climate.thermostat', 'temperature')-1)|round }}"

- alias: Notify when door is opened
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0002b6e9f4
    to: 'on'
  action:
    - service: notify.notify_person
      data:
        message: 'The door has been opened'

- alias: 'Set theme at startup'
  trigger:
   - platform: homeassistant
     event: start
  action:
    service: frontend.set_theme
    data:
      name: material_dark_red

- alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.notify
      data_template:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
