- alias: Turn on night lights on motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000122955e
    to: 'on'
  condition:
    condition: numeric_state
    entity_id: sensor.illumination_34ce0088f666
    below: 500
  action:
    service: light.turn_on
    entity_id: group.night_lights
    data:
      transition: 5

- alias: Turn off night lights after motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000122955e
      to: 'off'
      for:
        seconds: 10
  action:
    - service: light.turn_off
      entity_id: group.night_lights
      data:
        transition: 60

- alias: 'AQI warning'
  hide_entity: true
  trigger:
    platform: numeric_state
    entity_id:
      - sensor.aqi
    above: 25
    for: "00:10:00"
  action:
    - service: tts.google_translate_say
      entity_id: media_player.living_room_speaker
      data:
        message: 'Hazardous atmospheric conditions detected'

- alias: 'AQI control'
  hide_entity: false
  trigger:
    platform: time_pattern
    minutes: '/1'
  action:
    - service: script.ap_detect

- alias: 'Set theme at startup'
  hide_entity: true
  trigger:
   - platform: homeassistant
     event: start
  action:
    service: frontend.set_theme
    data:
      name: material_dark_red

- alias: Update Available Notification
  hide_entity: true
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.notify
      data_template:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
