default_config:

homeassistant:
  name: Home
  unit_system: metric
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 22
  unit_system: metric
  time_zone: Asia/Makassar
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - fd00::/8
        - 127.0.0.1
        - ::1
      allow_bypass_login: true
  customize: !include customize.yaml

http:
  base_url: https://home.dmit.ro
  server_port: 8123
  cors_allowed_origins:
    - https://home.dmit.ro
    - http://home.dmit.ro
    - http://home.local
  use_x_forwarded_for: true
  trusted_proxies:
    - 35.225.6.194
    - 127.0.0.1
    - ::1

tts:
  - platform: google_translate

frontend:
  themes: !include_dir_named themes

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 365

sensor:
  - platform: template
    sensors:
      outside_temperature:
        friendly_name: "Outside Temperature"
        unit_of_measurement: 'degrees'
        value_template: "{{ state_attr('weather.home', 'temperature') }}"
      home_temperature:
        friendly_name: "Home Temperature"
        unit_of_measurement: 'degrees'
        value_template: "{{ state_attr('fan.air_purifier', 'temperature') }}"
      outside_humidity:
        friendly_name: "Outside Humidity"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.home', 'humidity') }}"
      home_humidity:
        friendly_name: "Home Humidity"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('fan.air_purifier', 'humidity') }}"
      home_aqi:
        friendly_name: "Home AQI"
        unit_of_measurement: 'aqi'
        value_template: "{{ state_attr('fan.air_purifier', 'aqi') }}"

history_graph:
  gr1:
    name: Temperature
    entities:
      - sensor.outside_temperature
      - sensor.home_temperature
    hours_to_show: 24
    refresh: 60
  gr2:
    name: Humidity
    entities:
      - sensor.outside_humidity
      - sensor.home_humidity
    hours_to_show: 24
    refresh: 60

discovery:
  ignore:
    - homekit
    - yeelight

upnp:
  port_mapping: true

yeelight:
  devices:
    192.168.1.53:
      # yeelink-light-strip2_miap7569 7C-49-EB-B6-75-69
      name: Under Bed
      model: strip1
    192.168.1.52:
      # yeelink-light-color2_miapbfe4 7C-49-EB-AC-BF-E4
      name: Bedroom 2
      model: color2
    192.168.1.54:
      # yeelink-light-color2_miap0cf8 04-CF-8C-97-0C-F8
      name: Office 2
      model: color2
    192.168.1.55:
      # yeelink-light-color2_miap1a87 04-CF-8C-97-1A-87
      name: Office 1
      model: color2
    192.168.1.56:
      # yeelink-light-color2_miap2573 04-CF-8C-97-25-73
      name: Bedroom 1
      model: color2
    192.168.1.57:
      # yeelink-light-color2_miap46c7 04-CF-8C-A5-46-C7
      name: Cosmetic 2
      model: color2
    192.168.1.58:
      # yeelink-light-color2_miap4ea4 04-CF-8C-A5-4E-A4
      name: Cosmetic 1
      model: color2
    192.168.1.59:
      # yeelink-light-color2_miap356d 04-CF-8C-A0-35-6D
      name: Kitchen 2
      model: color2
    192.168.1.60:
      # yeelink-light-color2_miap43a0 04-CF-8C-A5-43-A0
      name: Kitchen 1
      model: color2

xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret gateway_key

fan:
  - platform: xiaomi_miio
    name: Air Purifier
    host: 192.168.1.51
    token: !secret purifier_key
    model: zhimi.airpurifier.ma2

remote:
  - platform: xiaomi_miio
    name: Remote
    host: 192.168.1.61
    token: !secret ir_key
    slot: 1
    timeout: 30
    hidden: true
    commands: !include ir_commands.yaml

# TODO: climate control, e.g. https://github.com/Anonym-tsk/homeassistant-climate-xiaomi-remote
